name: energize
description: Track your food and nutrition easily and fast.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.13.3+32

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  qr_code_scanner:
    git:
      url: https://codeberg.org/epinez/qr_code_scanner_revived
      ref: bfd6eb720da4b69d87a3a790f2da7346341acc0f
  openfoodfacts: ^3.25.1
  flutter_speed_dial: ^7.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  dio: ^5.9.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  json_serializable: ^6.11.1
  build_runner: ^2.8.0
  json_annotation: ^4.9.0
  table_calendar: ^3.2.0
  collection: ^1.19.1
  http: ^1.5.0
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.1+1
  fl_chart: ^1.1.1
  file_picker: ^10.3.3
  package_info_plus: ^8.3.0
  flutter_markdown: ^0.7.7+1
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  talker_flutter: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  watcher: ^1.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/food_databases/
    - assets/mondstern/
    - lib/services/food_database_bindings/swiss_food_composition_database/assets/
    - lib/pages/tab_settings/about_sub_page/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
