name: energize
description: Track your food and nutrition easily and fast.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.12.0+25

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
      ref: 86b7ca33af56e1dab07179f3a3a03784310ed65c
  openfoodfacts: ^3.18.1
  flutter_speed_dial: ^7.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  path: ^1.9.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  dio: ^5.7.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  json_annotation: ^4.9.0
  table_calendar: ^3.1.3
  collection: ^1.18.0
  http: ^1.2.2
  sqflite_common_ffi: ^2.3.4+4
  sqflite_common_ffi_web: ^0.4.5+4
  fl_chart: ^0.69.2
  file_picker: ^8.1.6
  package_info_plus: ^8.1.2
  flutter_markdown: ^0.7.4+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  watcher: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/food_databases/
    - assets/mondstern/
    - lib/services/food_database_bindings/swiss_food_composition_database/assets/
    - lib/pages/tab_settings/about_sub_page/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
