on:
  workflow_dispatch:
jobs:
  energize-build-debug-apk:
    runs-on: codeberg-small-lazy
    steps:
      - name: Checkout App to 'epinez/Energize'
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Update package lists
        run: |
          add-apt-repository ppa:fdroid/fdroidserver
          apt update
      - name: Android SDK Setup
        run: |
          apt install -y android-sdk sdkmanager
          export ANDROID_HOME=/usr/lib/android-sdk
          sdkmanager "cmdline-tools;latest"
          echo y | sdkmanager --licenses
      - name: Java Setup
        run: |
          apt install -y openjdk-21-jdk-headless
          update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
      - name: Flutter Setup
        run: |
          sed -i "/'tar',/N; /'tar',\n\s*'-xzf'/s/'-xzf'/'--no-same-owner','-xzf'/" submodules/flutter/packages/flutter_tools/lib/src/base/os.dart
          submodules/flutter/bin/flutter config --no-analytics
      - name: Flutter Prebuild
        run: |
          submodules/flutter/bin/flutter pub get
          submodules/flutter/bin/dart run build_runner build --delete-conflicting-outputs
      - name: Flutter Build Debug APK
        run: |
          submodules/flutter/bin/flutter build apk --debug
      - name: Upload Debug APK artifact
        uses: https://code.forgejo.org/actions/upload-artifact@v4
        with:
          name: Energize Debug APK
          path: build/app/outputs/flutter-apk/app-debug.apk
