// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'body_targets.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BodyTargets _$BodyTargetsFromJson(Map<String, dynamic> json) => BodyTargets(
  age: (json['age'] as num?)?.toInt() ?? 20,
  sex: $enumDecodeNullable(_$SexEnumMap, json['sex']) ?? Sex.male,
  weight: (json['weight'] as num?)?.toInt() ?? 80,
  height: (json['height'] as num?)?.toInt() ?? 180,
  activityLevel: (json['activityLevel'] as num?)?.toDouble() ?? 1.4,
  weightTarget:
      $enumDecodeNullable(_$WeightTargetEnumMap, json['weightTarget']) ??
      WeightTarget.maintaining,
  proteinRatio: (json['proteinRatio'] as num?)?.toDouble() ?? 20,
  carbsRatio: (json['carbsRatio'] as num?)?.toDouble() ?? 50,
  fatRatio: (json['fatRatio'] as num?)?.toDouble() ?? 30,
  caloriesTarget: (json['caloriesTarget'] as num?)?.toDouble() ?? 0.0,
  proteinTarget: (json['proteinTarget'] as num?)?.toDouble() ?? 0.0,
  carbsTarget: (json['carbsTarget'] as num?)?.toDouble() ?? 0.0,
  fatTarget: (json['fatTarget'] as num?)?.toDouble() ?? 0.0,
  vitaminATarget: (json['vitaminATarget'] as num?)?.toDouble() ?? 0.0,
  vitaminB1Target: (json['vitaminB1Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB2Target: (json['vitaminB2Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB3Target: (json['vitaminB3Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB5Target: (json['vitaminB5Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB6Target: (json['vitaminB6Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB7Target: (json['vitaminB7Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB9Target: (json['vitaminB9Target'] as num?)?.toDouble() ?? 0.0,
  vitaminB12Target: (json['vitaminB12Target'] as num?)?.toDouble() ?? 0.0,
  vitaminCTarget: (json['vitaminCTarget'] as num?)?.toDouble() ?? 0.0,
  vitaminDTarget: (json['vitaminDTarget'] as num?)?.toDouble() ?? 0.0,
  vitaminETarget: (json['vitaminETarget'] as num?)?.toDouble() ?? 0.0,
  vitaminKTarget: (json['vitaminKTarget'] as num?)?.toDouble() ?? 80.0,
  calciumTarget: (json['calciumTarget'] as num?)?.toDouble() ?? 0.0,
  chlorideTarget: (json['chlorideTarget'] as num?)?.toDouble() ?? 0.0,
  magnesiumTarget: (json['magnesiumTarget'] as num?)?.toDouble() ?? 0.0,
  phosphorusTarget: (json['phosphorusTarget'] as num?)?.toDouble() ?? 0.0,
  potassiumTarget: (json['potassiumTarget'] as num?)?.toDouble() ?? 0.0,
  sodiumTarget: (json['sodiumTarget'] as num?)?.toDouble() ?? 0.0,
  chromiumTarget: (json['chromiumTarget'] as num?)?.toDouble() ?? 0.0,
  ironTarget: (json['ironTarget'] as num?)?.toDouble() ?? 0.0,
  fluorineTarget: (json['fluorineTarget'] as num?)?.toDouble() ?? 0.0,
  iodineTarget: (json['iodineTarget'] as num?)?.toDouble() ?? 0.0,
  copperTarget: (json['copperTarget'] as num?)?.toDouble() ?? 0.0,
  manganeseTarget: (json['manganeseTarget'] as num?)?.toDouble() ?? 0.0,
  molybdenumTarget: (json['molybdenumTarget'] as num?)?.toDouble() ?? 0.0,
  seleniumTarget: (json['seleniumTarget'] as num?)?.toDouble() ?? 0.0,
  zincTarget: (json['zincTarget'] as num?)?.toDouble() ?? 0.0,
  monounsaturatedFatTarget:
      (json['monounsaturatedFatTarget'] as num?)?.toDouble() ?? 0.0,
  polyunsaturatedFatTarget:
      (json['polyunsaturatedFatTarget'] as num?)?.toDouble() ?? 0.0,
  omega3Target: (json['omega3Target'] as num?)?.toDouble() ?? 0.0,
  omega6Target: (json['omega6Target'] as num?)?.toDouble() ?? 0.0,
  saturatedFatTarget: (json['saturatedFatTarget'] as num?)?.toDouble() ?? 0.0,
  transFatTarget: (json['transFatTarget'] as num?)?.toDouble() ?? 0.0,
  cholesterolTarget: (json['cholesterolTarget'] as num?)?.toDouble() ?? 0.0,
  fiberTarget: (json['fiberTarget'] as num?)?.toDouble() ?? 0.0,
  sugarTarget: (json['sugarTarget'] as num?)?.toDouble() ?? 0.0,
  sugarAlcoholTarget: (json['sugarAlcoholTarget'] as num?)?.toDouble() ?? 0.0,
  starchTarget: (json['starchTarget'] as num?)?.toDouble() ?? 0.0,
  waterTarget: (json['waterTarget'] as num?)?.toDouble() ?? 0.0,
  caffeineTarget: (json['caffeineTarget'] as num?)?.toDouble() ?? 0.0,
  alcoholTarget: (json['alcoholTarget'] as num?)?.toDouble() ?? 0.0,
);

Map<String, dynamic> _$BodyTargetsToJson(BodyTargets instance) =>
    <String, dynamic>{
      'age': instance.age,
      'sex': _$SexEnumMap[instance.sex]!,
      'weight': instance.weight,
      'height': instance.height,
      'activityLevel': instance.activityLevel,
      'weightTarget': _$WeightTargetEnumMap[instance.weightTarget]!,
      'proteinRatio': instance.proteinRatio,
      'carbsRatio': instance.carbsRatio,
      'fatRatio': instance.fatRatio,
      'caloriesTarget': instance.caloriesTarget,
      'proteinTarget': instance.proteinTarget,
      'carbsTarget': instance.carbsTarget,
      'fatTarget': instance.fatTarget,
      'vitaminATarget': instance.vitaminATarget,
      'vitaminB1Target': instance.vitaminB1Target,
      'vitaminB2Target': instance.vitaminB2Target,
      'vitaminB3Target': instance.vitaminB3Target,
      'vitaminB5Target': instance.vitaminB5Target,
      'vitaminB6Target': instance.vitaminB6Target,
      'vitaminB7Target': instance.vitaminB7Target,
      'vitaminB9Target': instance.vitaminB9Target,
      'vitaminB12Target': instance.vitaminB12Target,
      'vitaminCTarget': instance.vitaminCTarget,
      'vitaminDTarget': instance.vitaminDTarget,
      'vitaminETarget': instance.vitaminETarget,
      'vitaminKTarget': instance.vitaminKTarget,
      'calciumTarget': instance.calciumTarget,
      'chlorideTarget': instance.chlorideTarget,
      'magnesiumTarget': instance.magnesiumTarget,
      'phosphorusTarget': instance.phosphorusTarget,
      'potassiumTarget': instance.potassiumTarget,
      'sodiumTarget': instance.sodiumTarget,
      'chromiumTarget': instance.chromiumTarget,
      'ironTarget': instance.ironTarget,
      'fluorineTarget': instance.fluorineTarget,
      'iodineTarget': instance.iodineTarget,
      'copperTarget': instance.copperTarget,
      'manganeseTarget': instance.manganeseTarget,
      'molybdenumTarget': instance.molybdenumTarget,
      'seleniumTarget': instance.seleniumTarget,
      'zincTarget': instance.zincTarget,
      'monounsaturatedFatTarget': instance.monounsaturatedFatTarget,
      'polyunsaturatedFatTarget': instance.polyunsaturatedFatTarget,
      'omega3Target': instance.omega3Target,
      'omega6Target': instance.omega6Target,
      'saturatedFatTarget': instance.saturatedFatTarget,
      'transFatTarget': instance.transFatTarget,
      'cholesterolTarget': instance.cholesterolTarget,
      'fiberTarget': instance.fiberTarget,
      'sugarTarget': instance.sugarTarget,
      'sugarAlcoholTarget': instance.sugarAlcoholTarget,
      'starchTarget': instance.starchTarget,
      'waterTarget': instance.waterTarget,
      'caffeineTarget': instance.caffeineTarget,
      'alcoholTarget': instance.alcoholTarget,
    };

const _$SexEnumMap = {Sex.male: 'male', Sex.female: 'female'};

const _$WeightTargetEnumMap = {
  WeightTarget.strongLoss: 'strong_loss',
  WeightTarget.moderateLoss: 'moderate_loss',
  WeightTarget.slightLoss: 'slight_loss',
  WeightTarget.maintaining: 'maintaining',
  WeightTarget.slightGain: 'slight_gain',
  WeightTarget.moderateGain: 'moderate_gain',
  WeightTarget.strongGain: 'strong_gain',
};
